version: '3'
services:
  db:
    image: mysql:8.0.28
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
